/**
 * FKP Edge Inference — Bare-Metal C Implementation
 *
 * This file implements the single matrix-vector multiply that constitutes
 * the entire edge device computation:
 *
 *     logits[c] = W_edge[p x c]^T @ z[p] + bias[c]
 *
 * Complexity: O(p * c) MACs.
 * For p=64, c=38: 2,432 MACs => microsecond latency on Cortex-M4.
 *
 * The file fkp_inference.h is auto-generated by export_to_c.py and
 * contains the flattened (row-major) weight arrays.
 *
 * Compile locally for verification:
 *     gcc -O2 -Wall -o fkp_sim edge_deployment/src/main.c -lm
 *
 * For ARM Cortex-M with CMSIS-DSP (replace fkp_matvec with arm_mat_vec_mult):
 *     arm-none-eabi-gcc -mcpu=cortex-m4 -mfpu=fpv4-sp-d16 -mfloat-abi=hard ...
 *
 * Reference: §5 "Edge Export & TinyML" and §3.4 "Split-Edge Deployment"
 */

#include <stdio.h>
#include <stdlib.h>
#include <string.h>
#include <math.h>

/* Auto-generated weight header — swap for your specific model export */
#include "../include/fkp_inference.h"

/* ── Configuration ────────────────────────────────────────────────────────── */
#define FKP_SOFTMAX_TEMP  1.0f   /* Temperature for optional softmax */

/* ── Forward declarations ─────────────────────────────────────────────────── */
static void fkp_matvec(
    const float *W,       /* row-major matrix (rows x cols) */
    const float *x,       /* input vector (rows,) */
    float       *out,     /* output vector (cols,) */
    int          rows,
    int          cols
);

static void fkp_add_bias(float *logits, const float *bias, int n);
static int  fkp_argmax(const float *vec, int n);
static void fkp_softmax(float *vec, int n, float temperature);
static void fkp_print_logits(const float *logits, int n, int predicted_class);

/* ── Main inference function ──────────────────────────────────────────────── */

/**
 * fkp_infer - Run one FKP edge inference.
 *
 * @param z               Projected feature vector of dimension FKP_RANK_P.
 *                        Computed on gateway: z = U_p^T @ tilde_E(x).
 * @param logits_out      Output buffer of size FKP_N_CLASSES.
 * @return                Predicted class index (argmax of logits).
 */
int fkp_infer(const float *z, float *logits_out)
{
    /* Step 1: logits = W_edge^T @ z
     *
     * W_edge is stored row-major with shape (FKP_RANK_P, FKP_N_CLASSES).
     * We compute: logits[j] = sum_i W_edge[i * FKP_N_CLASSES + j] * z[i]
     * which is a matrix-vector multiply with W_edge^T.
     */
    memset(logits_out, 0, FKP_N_CLASSES * sizeof(float));

    for (int i = 0; i < FKP_RANK_P; ++i) {
        for (int j = 0; j < FKP_N_CLASSES; ++j) {
            logits_out[j] += fkp_W_edge[i * FKP_N_CLASSES + j] * z[i];
        }
    }

    /* Step 2: logits += bias (H_bar) */
    fkp_add_bias(logits_out, fkp_bias, FKP_N_CLASSES);

    /* Return argmax (the predicted class) */
    return fkp_argmax(logits_out, FKP_N_CLASSES);
}

/* ── Gateway projection (reference — runs on gateway, NOT MCU) ───────────── */

/**
 * fkp_project_gateway - Project conditioned feature to p-dimensional vector.
 *
 * This function runs on the GATEWAY, not the MCU.  It is included here
 * for integration testing: the C output of this projection should match
 * the PyTorch output from the Python pipeline exactly.
 *
 * @param tilde_E  Conditioned feature of dimension FKP_FEAT_DIM.
 * @param z_out    Output projection of dimension FKP_RANK_P.
 */
void fkp_project_gateway(const float *tilde_E, float *z_out)
{
    /* z = U_p^T @ tilde_E
     * U_p is stored row-major with shape (FKP_FEAT_DIM, FKP_RANK_P).
     * z[j] = sum_i U_p[i * FKP_RANK_P + j] * tilde_E[i]
     */
    memset(z_out, 0, FKP_RANK_P * sizeof(float));
    for (int i = 0; i < FKP_FEAT_DIM; ++i) {
        for (int j = 0; j < FKP_RANK_P; ++j) {
            z_out[j] += fkp_U_p[i * FKP_RANK_P + j] * tilde_E[i];
        }
    }
}

/* ── Utility functions ────────────────────────────────────────────────────── */

static void fkp_matvec(
    const float *W, const float *x, float *out, int rows, int cols)
{
    memset(out, 0, cols * sizeof(float));
    for (int i = 0; i < rows; ++i) {
        for (int j = 0; j < cols; ++j) {
            out[j] += W[i * cols + j] * x[i];
        }
    }
}

static void fkp_add_bias(float *logits, const float *bias, int n)
{
    for (int i = 0; i < n; ++i) {
        logits[i] += bias[i];
    }
}

static int fkp_argmax(const float *vec, int n)
{
    int best = 0;
    for (int i = 1; i < n; ++i) {
        if (vec[i] > vec[best]) best = i;
    }
    return best;
}

static void fkp_softmax(float *vec, int n, float temperature)
{
    float max_val = vec[0];
    for (int i = 1; i < n; ++i) {
        if (vec[i] > max_val) max_val = vec[i];
    }
    float sum = 0.0f;
    for (int i = 0; i < n; ++i) {
        vec[i] = expf((vec[i] - max_val) / temperature);
        sum += vec[i];
    }
    for (int i = 0; i < n; ++i) {
        vec[i] /= sum;
    }
}

static void fkp_print_logits(const float *logits, int n, int predicted_class)
{
    printf("[FKP] Predicted class: %d\n", predicted_class);
    printf("[FKP] Top-5 logits:\n");
    /* Simple selection for top-5 display (not optimised) */
    for (int k = 0; k < (n < 5 ? n : 5); ++k) {
        int best = 0;
        float best_val = -1e38f;
        for (int i = 0; i < n; ++i) {
            if (logits[i] > best_val) { best_val = logits[i]; best = i; }
        }
        printf("  class %3d : %.4f\n", best, best_val);
        /* Suppress this class for next iteration — hack for display only */
        ((float *)logits)[best] = -1e38f;
    }
}

/* ── Entry point (simulation / verification) ─────────────────────────────── */

int main(void)
{
    printf("=== FKP Edge Inference Simulator ===\n");
    printf("    Rank p = %d, Classes c = %d\n", FKP_RANK_P, FKP_N_CLASSES);
    printf("    Edge model: %.2f KB\n",
           (float)(FKP_RANK_P * FKP_N_CLASSES + FKP_N_CLASSES) * 4.0f / 1024.0f);
    printf("    Payload  : %d bytes (p x float32)\n\n", FKP_RANK_P * 4);

    /* Generate a dummy p-dimensional projection vector z (all ones) */
    float z[FKP_RANK_P];
    for (int i = 0; i < FKP_RANK_P; ++i) z[i] = 1.0f;

    /* Run inference */
    float logits[FKP_N_CLASSES];
    int predicted = fkp_infer(z, logits);

    /* Display results */
    printf("[FKP] Input: z = [1.0, 1.0, ..., 1.0] (p=%d)\n", FKP_RANK_P);
    fkp_print_logits(logits, FKP_N_CLASSES, predicted);

    printf("\n[FKP] MACs = p * c = %d * %d = %d\n",
           FKP_RANK_P, FKP_N_CLASSES, FKP_RANK_P * FKP_N_CLASSES);

    return EXIT_SUCCESS;
}
