/* Auto-generated by FKP export_to_c.py — placeholder template */
/* Run: python edge_deployment/export_to_c.py --weights_dir outputs/<run> */
/* to populate this file with real trained weights.                        */

#ifndef FKP_INFERENCE_H
#define FKP_INFERENCE_H

/* ── Placeholder dimensions (override after export) ───────────────────── */
#define FKP_FEAT_DIM    768   /* Total conditioned feature dim D */
#define FKP_RANK_P       64   /* Projection rank p */
#define FKP_N_CLASSES    38   /* Number of output classes (PlantVillage) */

/* ── Placeholder weight arrays ────────────────────────────────────────── */
/* These arrays are populated by export_to_c.py from trained .npy files.  */
/* Do NOT edit manually.                                                   */

/* Gateway projection matrix U_p: (FKP_FEAT_DIM, FKP_RANK_P), row-major. */
/* Byte size: FKP_FEAT_DIM * FKP_RANK_P * 4 = 196,608 bytes ~ 192 KB     */
/* NOTE: U_p stays on the gateway. Included here for simulation only.     */
extern const float fkp_U_p[FKP_FEAT_DIM * FKP_RANK_P];

/* Edge weight matrix W_edge: (FKP_RANK_P, FKP_N_CLASSES), row-major.    */
/* Byte size: FKP_RANK_P * FKP_N_CLASSES * 4 = 9,728 bytes ~ 9.5 KB      */
extern const float fkp_W_edge[FKP_RANK_P * FKP_N_CLASSES];

/* Bias vector b = H_bar: (FKP_N_CLASSES,).                               */
/* Byte size: FKP_N_CLASSES * 4 = 152 bytes                               */
extern const float fkp_bias[FKP_N_CLASSES];

#endif /* FKP_INFERENCE_H */
