"""
Export FKP Weight Matrices to C Header File.

Converts NumPy/PyTorch tensors (U_p, W_edge, bias) into a self-contained
C header file that can be flashed directly to an ESP32 / STM32 / RP2040.

Usage:
    python edge_deployment/export_to_c.py \
        --weights_dir outputs/plantvillage_resnet50 \
        --output edge_deployment/include/fkp_inference.h \
        --model_name FKP_PlantVillage_ResNet50

The generated header contains:
    - FKP_RANK_P     : projection rank p
    - FKP_N_CLASSES  : number of output classes c
    - fkp_U_p[]      : gateway projection matrix U_p (D x p), row-major
    - fkp_W_edge[]   : edge weight matrix W_edge (p x c), row-major
    - fkp_bias[]     : bias vector H_bar (c,)

Reference:
    §5 "Edge Export & TinyML" in the intern onboarding guide.
"""

from __future__ import annotations

import argparse
import datetime
import sys
from pathlib import Path

import numpy as np


def array_to_c(
    name: str,
    arr: np.ndarray,
    dtype: str = "float",
) -> str:
    """Serialise a NumPy array to a C const float array literal.

    Parameters
    ----------
    name : str
        C variable name.
    arr : np.ndarray
        Array to serialise (any shape; flattened row-major).
    dtype : str
        C type string.  Default: 'float' (32-bit).

    Returns
    -------
    str
        C source snippet defining the array.
    """
    flat = arr.flatten().astype(np.float32)
    n = len(flat)
    lines = [f"const {dtype} {name}[{n}] = {{"]
    # 8 values per line for readability
    for i in range(0, n, 8):
        chunk = flat[i : i + 8]
        formatted = ", ".join(f"{v:.8e}f" for v in chunk)
        comma = "," if i + 8 < n else ""
        lines.append(f"    {formatted}{comma}")
    lines.append("};")
    return "\n".join(lines)


def export_to_c_header(
    U_p: np.ndarray,
    W_edge: np.ndarray,
    bias: np.ndarray,
    output_path: str | Path,
    model_name: str = "FKP",
) -> None:
    """Write a C header file with all FKP edge inference constants.

    Parameters
    ----------
    U_p : np.ndarray
        Gateway projection matrix of shape (D, p).
    W_edge : np.ndarray
        Edge weight matrix of shape (p, c).
    bias : np.ndarray
        Bias vector of shape (c,).
    output_path : str or Path
        Destination .h file path.
    model_name : str
        Prefix for C macro guards and variable names.
    """
    D, p = U_p.shape
    p2, c = W_edge.shape
    assert p == p2, f"Shape mismatch: U_p has p={p}, W_edge has p={p2}"
    assert bias.shape == (c,), f"bias must be (c,)={c}, got {bias.shape}"

    guard = model_name.upper().replace(" ", "_").replace("-", "_") + "_H"
    ts = datetime.datetime.utcnow().strftime("%Y-%m-%d %H:%M UTC")

    header_lines = [
        f"/* Auto-generated by FKP export_to_c.py — {ts} */",
        f"/* Model: {model_name}  |  D={D}, p={p}, c={c} */",
        f"/* Do NOT edit manually — regenerate with export_to_c.py */",
        "",
        f"#ifndef {guard}",
        f"#define {guard}",
        "",
        f"#define FKP_FEAT_DIM    {D}   /* Total conditioned feature dim D */",
        f"#define FKP_RANK_P      {p}   /* Projection rank p */",
        f"#define FKP_N_CLASSES   {c}   /* Number of output classes */",
        "",
        "/* Gateway projection matrix U_p: shape (D, p), row-major. */",
        "/* On gateway: z = U_p^T @ tilde_E  =>  dim (p,)          */",
        array_to_c("fkp_U_p", U_p),
        "",
        "/* Edge weight matrix W_edge = Sigma_p @ V_p^T: shape (p, c), row-major. */",
        "/* On MCU: logits = W_edge^T @ z + bias  =>  dim (c,)                    */",
        array_to_c("fkp_W_edge", W_edge),
        "",
        "/* Bias vector b = H_bar (teacher mean logit): shape (c,). */",
        array_to_c("fkp_bias", bias),
        "",
        f"#endif /* {guard} */",
        "",
    ]

    Path(output_path).parent.mkdir(parents=True, exist_ok=True)
    with open(output_path, "w") as f:
        f.write("\n".join(header_lines))

    print(f"[FKP] Exported C header: {output_path}")
    print(f"      D={D}, p={p}, c={c}")
    print(f"      Edge model: {(p * c + c) * 4 / 1024:.2f} KB")
    print(f"      Payload   : {p * 4} bytes  ({p} x float32)")
    print(f"      MACs      : {p * c}")


def load_weights(weights_dir: str | Path) -> tuple[np.ndarray, np.ndarray, np.ndarray]:
    """Load saved FKP weights from a directory.

    Expects files:
        {weights_dir}/U_p.npy     — gateway projection matrix
        {weights_dir}/W_edge.npy  — edge weight matrix
        {weights_dir}/bias.npy    — bias vector (H_bar)

    Parameters
    ----------
    weights_dir : str or Path
        Directory containing the .npy weight files.

    Returns
    -------
    U_p, W_edge, bias : tuple[np.ndarray, ...]
    """
    weights_dir = Path(weights_dir)
    U_p = np.load(weights_dir / "U_p.npy")
    W_edge = np.load(weights_dir / "W_edge.npy")
    bias = np.load(weights_dir / "bias.npy")
    return U_p, W_edge, bias


def main() -> None:
    parser = argparse.ArgumentParser(
        description="Export FKP weights to a C header file for MCU deployment."
    )
    parser.add_argument(
        "--weights_dir",
        type=str,
        required=True,
        help="Directory containing U_p.npy, W_edge.npy, bias.npy",
    )
    parser.add_argument(
        "--output",
        type=str,
        default="edge_deployment/include/fkp_inference.h",
        help="Output .h file path",
    )
    parser.add_argument(
        "--model_name",
        type=str,
        default="FKP",
        help="Model name prefix for C macro guard",
    )
    args = parser.parse_args()

    try:
        U_p, W_edge, bias = load_weights(args.weights_dir)
    except FileNotFoundError as e:
        print(f"[ERROR] {e}", file=sys.stderr)
        sys.exit(1)

    export_to_c_header(U_p, W_edge, bias, args.output, model_name=args.model_name)


if __name__ == "__main__":
    main()
